
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/myown?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-wait: 10000
        max-idle: 500
    timeout: 0


server:
  port: 9999
mybatis:
  mapper-locations: classpath:/mapper/**.xml
  type-aliases-package: com.example.demo.pojo
  check-config-location:classpath: /resources/mybatis-config.xml


